# Generated by Django 3.0.5 on 2020-04-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='cases',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='deaths',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
