# Generated by Django 3.0.5 on 2020-04-06 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0002_auto_20200406_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='county',
            name='deaths',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='butter.County')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('county', 'date')},
            },
        ),
    ]
