# Generated by Django 3.0.5 on 2020-04-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0003_auto_20200406_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-date']},
        ),
    ]
