# Generated by Django 3.0.5 on 2020-04-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0004_auto_20200411_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
    ]
