# Generated by Django 3.0.5 on 2020-04-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0005_auto_20200411_0435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-date']},
        ),
    ]
