# Generated by Django 3.0.5 on 2020-04-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0006_auto_20200411_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
    ]
